const $=id=>document.getElementById(id);
let state=null,timer=null,syncing=false,lastVersion='',expanded=false;
const LIVE_API='https://pc28.help/api/keno.json?nbr=100';
const classify=n=>({size:n<=13?'小':'大',oe:n%2?'单':'双',combo:(n<=13?'小':'大')+(n%2?'单':'双')});
function fmt(sec){if(sec==null||sec<0)return'00:00';sec=Math.max(0,Math.floor(sec));const m=Math.floor(sec/60),s=sec%60;return`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function kenoABC(s){const a=String(s||'').split(/[,\s]+/).filter(Boolean).map(Number);if(a.length<19)return null;const g=x=>x.reduce((z,i)=>z+(a[i]||0),0)%10;return[g([1,4,7,10,13,16]),g([2,5,8,11,14,17]),g([3,6,9,12,15,18])]}
function parseCountdown(s){const a=String(s||'').split(':').map(Number);if(a.some(Number.isNaN))return 0;return a.length===2?a[0]*60+a[1]:a.length===3?a[0]*3600+a[1]*60+a[2]:0}
function autoReference(rows){const combos=['大单','大双','小单','小双'],recent=rows.slice(0,30),score=Object.fromEntries(combos.map(c=>[c,1.2])),why=[];recent.forEach((r,i)=>score[r.combo]+=1.1*(1-i/Math.max(30,recent.length+1)));const l8=recent.slice(0,8),cnt=Object.fromEntries(combos.map(c=>[c,0]));l8.forEach(r=>cnt[r.combo]++);if(l8.length>=4){const mn=Math.min(...Object.values(cnt));combos.forEach(c=>{if(cnt[c]===mn)score[c]+=.9});why.push('近8期回补')}if(recent.length){const last=recent[0].combo,op={'大双':'小单','小单':'大双','大单':'小双','小双':'大单'}[last];let n=0;for(const r of recent){if(r.combo===last)n++;else break}if(n>=2){score[op]+=Math.min(2.4,n*.6);score[last]-=Math.min(1,n*.2);why.push(`${last}连开${n}期修正`)}}const rank=Object.entries(score).sort((a,b)=>b[1]-a[1]),total=rank.reduce((s,[,v])=>s+Math.max(v,.1),0);return{picks:rank.slice(0,2).map(([name,v],i)=>({name,confidence:Math.max(45,Math.min(72,Math.round(43+Math.max(v,.1)/total*58-i*2)))})),reason:why.slice(0,2).join('；')||'根据近期历史走势自动生成'}}
function startCountdown(){if(timer)return;timer=setInterval(()=>{const end=Number(state?.countdownEndsAt||0);$('countdown').textContent=end?fmt((end-Date.now())/1000):(state?.countdown||'--:--')},1000)}
function getRows(s){return Object.values(s?.comparisons||{}).filter(x=>x.status==='已开奖').sort((a,b)=>Number(b.issue)-Number(a.issue))}
function renderStats(s){const rows=getRows(s),hit=rows.filter(x=>x.autoResult==='对').length;$('settledCount').textContent=rows.length;$('hitCount').textContent=hit;$('hitRate').textContent=rows.length?`${(hit/rows.length*100).toFixed(1)}%`:'--'}
function renderHistory(s){const all=getRows(s),rows=all.slice(0,expanded?50:10),box=$('historyList');if(!rows.length){box.innerHTML='<div class="empty">新期开奖后会自动积累核对记录</div>';$('moreBtn').hidden=true;return}box.innerHTML=rows.map(x=>`<div class="history-row"><div class="actual"><strong>#${x.issue}</strong><span>${x.actualABC||'--'} = ${x.actualSum??'--'} · ${x.actualCombo||'--'}</span></div><div class="auto-ref">${(x.autoPicks||[]).join(' / ')||'--'}</div><div class="judge ${x.autoResult==='对'?'ok':'bad'}">${x.autoResult||'待'}</div></div>`).join('');$('moreBtn').hidden=all.length<=10;$('moreBtn').textContent=expanded?'收起记录':'展开更多记录'}
function render(s,source='云端'){const latest=s.latestDraw,a=s.autoReference,p=a?.picks||[];$('issueText').textContent=latest?.issue?`最新：第 ${latest.issue} 期 · ${latest.abc||'--'} = ${latest.sum} · ${latest.combo}`:'等待开奖数据';$('nextIssueText').textContent=a?.issue?`第 ${a.issue} 期`:'等待分析';$('pick1').textContent=p[0]?.name||'--';$('pick2').textContent=p[1]?.name||'--';$('score1').textContent=`参考度 ${p[0]?.confidence??'--'}%`;$('score2').textContent=`参考度 ${p[1]?.confidence??'--'}%`;$('reason').textContent=a?.reason||'根据近期历史走势自动分析。';renderStats(s);renderHistory(s);const d=s.updatedAt?new Date(s.updatedAt):new Date();$('lastSync').textContent=d.toLocaleTimeString('zh-CN',{hour12:false,hour:'2-digit',minute:'2-digit',second:'2-digit'});$('syncHint').textContent=`${source}实时更新 · 下一期 ${s.nextIssue||'--'}`;$('onlineText').textContent='实时';startCountdown()}
async function loadLive(){const r=await fetch(`${LIVE_API}&_=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error('live');const j=await r.json(),a=Array.isArray(j?.data)?j.data:[];const rows=a.map(o=>{const abc=kenoABC(o.nbrs),issue=String(o.nbr||'');if(!abc||!issue)return null;const sum=abc.reduce((x,y)=>x+y,0);return{issue,abc:abc.join('+'),sum,...classify(sum),date:o.date||'',time:o.time||''}}).filter(Boolean);if(!rows.length)throw Error('parse');const latest=rows[0],next=/^\d+$/.test(latest.issue)?String(BigInt(latest.issue)+1n):latest.issue;const ar=autoReference(rows),sec=parseCountdown(j.countdown);state={...(state||{}),updatedAt:new Date().toISOString(),latestDraw:latest,nextIssue:next,countdown:j.countdown||'',countdownEndsAt:sec?Date.now()+sec*1000:null,drawHistory:rows,autoReference:{issue:next,...ar}};render(state,'开奖源')}
async function loadCloud(){const r=await fetch(`data/state.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error('cloud');const next=await r.json(),ver=String(next.updatedAt||'')+String(next.latestDraw?.issue||'');state={...(state||{}),...next};if(ver!==lastVersion){lastVersion=ver;render(state,'云端')}}
async function sync(force=false){if(syncing||document.hidden&&!force)return;syncing=true;try{try{await loadLive()}catch{await loadCloud()}}catch{$('syncHint').textContent='同步失败，正在自动重试';$('onlineText').textContent='重试中'}finally{syncing=false}}
$('syncBtn').addEventListener('click',()=>sync(true));$('moreBtn').addEventListener('click',()=>{expanded=!expanded;renderHistory(state)});sync(true);setInterval(()=>sync(false),5000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync(true)});