const $=id=>document.getElementById(id);
let state=null,syncing=false,expanded=false,localEnd=0;
const LIVE_API='https://pc28.help/api/keno.json?nbr=100';
const PERIOD=210000;
const classify=n=>({size:n<=13?'小':'大',oe:n%2?'单':'双',combo:(n<=13?'小':'大')+(n%2?'单':'双')});
function fmt(sec){sec=Math.max(0,Math.floor(Number(sec)||0));const m=Math.floor(sec/60),s=sec%60;return`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function kenoABC(s){const a=String(s||'').split(/[,\s]+/).filter(Boolean).map(Number);if(a.length<19)return null;const g=x=>x.reduce((z,i)=>z+(a[i]||0),0)%10;return[g([1,4,7,10,13,16]),g([2,5,8,11,14,17]),g([3,6,9,12,15,18])]}
function parseCountdown(s){const a=String(s||'').split(':').map(Number);if(a.some(Number.isNaN))return 0;return a.length===2?a[0]*60+a[1]:a.length===3?a[0]*3600+a[1]*60+a[2]:0}
function autoReference(rows){const combos=['大单','大双','小单','小双'],recent=rows.slice(0,30),score=Object.fromEntries(combos.map(c=>[c,1.2]));recent.forEach((r,i)=>score[r.combo]+=1.1*(1-i/30));const rank=Object.entries(score).sort((a,b)=>b[1]-a[1]),total=rank.reduce((s,[,v])=>s+v,0);return{picks:rank.slice(0,2).map(([name,v],i)=>({name,confidence:Math.max(45,Math.min(72,Math.round(43+v/total*58-i*2)))})),reason:'根据最新开奖历史实时更新'}}
function getRows(s){return Object.values(s?.comparisons||{}).filter(x=>x.status==='已开奖').sort((a,b)=>Number(b.issue)-Number(a.issue))}
function renderStats(s){const rows=getRows(s),hit=rows.filter(x=>x.autoResult==='对').length;$('settledCount').textContent=rows.length;$('hitCount').textContent=hit;$('hitRate').textContent=rows.length?`${(hit/rows.length*100).toFixed(1)}%`:'--'}
function renderHistory(s){const all=getRows(s),rows=all.slice(0,expanded?50:10),box=$('historyList');if(!rows.length){box.innerHTML='<div class="empty">新期开奖后会自动积累核对记录</div>';$('moreBtn').hidden=true;return}box.innerHTML=rows.map(x=>`<div class="history-row"><div class="actual"><strong>#${x.issue}</strong><span>${x.actualABC||'--'} = ${x.actualSum??'--'} · ${x.actualCombo||'--'}</span></div><div class="auto-ref">${(x.autoPicks||[]).join(' / ')||'--'}</div><div class="judge ${x.autoResult==='对'?'ok':'bad'}">${x.autoResult||'待'}</div></div>`).join('');$('moreBtn').hidden=all.length<=10;$('moreBtn').textContent=expanded?'收起记录':'展开更多记录'}
function ensureClock(){const cloud=Number(state?.countdownEndsAt||0);if(cloud>Date.now()+1000){localEnd=cloud;return}if(!localEnd||localEnd<=Date.now()){localEnd=Date.now()+PERIOD}}
function paint(source='实时'){if(!state)return;const latest=state.latestDraw,a=state.autoReference,p=a?.picks||[];$('issueText').textContent=latest?.issue?`最新：第 ${latest.issue} 期 · ${latest.abc||'--'} = ${latest.sum} · ${latest.combo}`:'等待开奖数据';$('nextIssueText').textContent=a?.issue?`第 ${a.issue} 期`:'等待分析';$('pick1').textContent=p[0]?.name||'--';$('pick2').textContent=p[1]?.name||'--';$('score1').textContent=`参考度 ${p[0]?.confidence??'--'}%`;$('score2').textContent=`参考度 ${p[1]?.confidence??'--'}%`;$('reason').textContent=a?.reason||'等待分析';renderStats(state);renderHistory(state);ensureClock();$('onlineText').textContent=source}
function tickClock(){if(!state)return;ensureClock();const left=(localEnd-Date.now())/1000;$('countdown').textContent=fmt(left);if(left<=1){$('syncHint').textContent='正在等待新期开奖…';sync(true)}}
async function fetchTimeout(url,ms=1800){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{cache:'no-store',signal:c.signal})}finally{clearTimeout(t)}}
async function loadLive(){const r=await fetchTimeout(`${LIVE_API}&_=${Date.now()}`,1800);if(!r.ok)throw Error();const j=await r.json(),raw=Array.isArray(j?.data)?j.data:[],rows=raw.map(o=>{const abc=kenoABC(o.nbrs),issue=String(o.nbr||'');if(!abc||!issue)return null;const sum=abc.reduce((x,y)=>x+y,0);return{issue,abc:abc.join('+'),sum,...classify(sum)}}).filter(Boolean);if(!rows.length)throw Error();const latest=rows[0],next=String(BigInt(latest.issue)+1n),ar=autoReference(rows),sec=parseCountdown(j.countdown);state={...(state||{}),updatedAt:new Date().toISOString(),latestDraw:latest,nextIssue:next,countdown:j.countdown||'',countdownEndsAt:sec?Date.now()+sec*1000:null,drawHistory:rows,autoReference:{issue:next,...ar}};localEnd=state.countdownEndsAt||Date.now()+PERIOD;paint('实时');$('lastSync').textContent=new Date().toLocaleTimeString('zh-CN',{hour12:false});$('syncHint').textContent=`实时开奖源 · 下一期 ${next}`}
async function loadCloud(){const r=await fetch(`data/state.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error();const cloud=await r.json(),oldIssue=state?.latestDraw?.issue;state={...(state||{}),...cloud};if(oldIssue&&state.latestDraw?.issue!==oldIssue)localEnd=0;ensureClock();paint('同步中');$('lastSync').textContent=new Date().toLocaleTimeString('zh-CN',{hour12:false});$('syncHint').textContent=`自动同步 · 下一期 ${state.nextIssue||'--'}`}
async function sync(force=false){if(syncing||document.hidden&&!force)return;syncing=true;try{try{await loadLive()}catch{await loadCloud()}}catch{$('syncHint').textContent='正在自动重连…';$('onlineText').textContent='重连中';ensureClock()}finally{syncing=false}}
$('syncBtn').addEventListener('click',()=>sync(true));$('moreBtn').addEventListener('click',()=>{expanded=!expanded;renderHistory(state)});
setInterval(tickClock,250);setInterval(()=>sync(false),3000);sync(true);document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync(true)});