import fs from 'fs';

const FILE='data/state.json';
const BASE='https://pc28.help';
const COMBOS=['大单','大双','小单','小双'];
const TIMEOUT=5500;

const SOURCES=[
  {id:'pc28668',url:'https://www.pc28668.com/',w:1,parse(h){const a=[...h.matchAll(/(\d{7})[\s\S]{0,140}?([大小])\s*([单双])/g)];if(!a.length)return null;const m=a[0];return {issue:m[1],kind:'combo',size:m[2],oe:m[3]}}},
  {id:'canada28org',url:'https://kj.canada28.org/jndpc28jk/index.php?i=5&type=10',w:.82,parse(h){const t=h.replace(/<[^>]+>/g,' ').replace(/\s+/g,' '),m=t.match(/(\d{7})[\s\S]{0,120}?(杀中|杀小边|杀大边)/);return m?{issue:m[1],kind:'exclude',value:m[2]}:null}},
  {id:'pc28ai',url:'https://www.pc28.ai/',w:.72,parse(h){const t=h.replace(/<[^>]+>/g,' ').replace(/\s+/g,' '),issue=(t.match(/第\s*(\d{7})\s*期/)||[])[1],num=(t.match(/预测号码\s*[:：]?\s*(\d{1,2})/)||[])[1],c=t.match(/(?:算法1|智能预测|AI预测|预测)[\s\S]{0,260}?([大小])[\s\S]{0,80}?([单双])/);if(issue&&num!=null)return {issue,kind:'sum',sum:Number(num)};return issue&&c?{issue,kind:'combo',size:c[1],oe:c[2]}:null}}
];

const classify=n=>({size:n<=13?'小':'大',oe:n%2?'单':'双',combo:(n<=13?'小':'大')+(n%2?'单':'双')});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));

async function fetchT(url,ms=TIMEOUT){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,redirect:'follow',headers:{'user-agent':'Mozilla/5.0 jnd28-updater','accept':'*/*'}});if(!r.ok)throw Error('HTTP '+r.status);return r}finally{clearTimeout(t)}}
function kenoABC(s){const a=String(s||'').split(/[,\s]+/).filter(Boolean).map(Number);if(a.length<19)return null;const g=x=>x.reduce((z,i)=>z+(a[i]||0),0)%10;return [g([1,4,7,10,13,16]),g([2,5,8,11,14,17]),g([3,6,9,12,15,18])];}
function parseCountdown(s){if(!s)return 0;const a=String(s).split(':').map(Number);if(a.some(Number.isNaN))return 0;if(a.length===2)return a[0]*60+a[1];if(a.length===3)return a[0]*3600+a[1]*60+a[2];return 0;}
async function drawData(){const j=await (await fetchT(`${BASE}/api/keno.json?nbr=100&_=${Date.now()}`,8000)).json();const a=Array.isArray(j?.data)?j.data:[];const rows=a.map(o=>{const abc=kenoABC(o.nbrs),issue=String(o.nbr||'');if(!abc||!issue)return null;const sum=abc.reduce((x,y)=>x+y,0);return {issue,abc:abc.join('+'),sum,...classify(sum),date:o.date||'',time:o.time||''}}).filter(Boolean);if(!rows.length)throw Error('开奖数据无法解析');const sec=parseCountdown(j.countdown);return {rows,countdown:j.countdown||'',countdownEndsAt:sec?Date.now()+sec*1000:null};}
function autoReference(rows){const recent=rows.slice(0,30),score=Object.fromEntries(COMBOS.map(c=>[c,1.2])),why=[];recent.forEach((r,i)=>score[r.combo]+=1.1*(1-i/Math.max(30,recent.length+1)));const l8=recent.slice(0,8),cnt=Object.fromEntries(COMBOS.map(c=>[c,0]));l8.forEach(r=>cnt[r.combo]++);if(l8.length>=4){const mn=Math.min(...Object.values(cnt));COMBOS.forEach(c=>{if(cnt[c]===mn)score[c]+=.9});why.push('近8期回补')}if(recent.length){const last=recent[0].combo,op={'大双':'小单','小单':'大双','大单':'小双','小双':'大单'}[last];let n=0;for(const r of recent){if(r.combo===last)n++;else break}if(n>=2){score[op]+=Math.min(2.4,n*.6);score[last]-=Math.min(1,n*.2);why.push(`${last}连开${n}期修正`)}}const rank=Object.entries(score).sort((a,b)=>b[1]-a[1]),total=rank.reduce((s,[,v])=>s+Math.max(v,.1),0);return {picks:rank.slice(0,2).map(([name,v],i)=>({name,confidence:Math.max(45,Math.min(72,Math.round(43+Math.max(v,.1)/total*58-i*2)))})),reason:why.slice(0,2).join('；')||'根据近期历史走势自动生成'};}
function baseScores(){const w=Array(28).fill(0);for(let a=0;a<10;a++)for(let b=0;b<10;b++)for(let c=0;c<10;c++)w[a+b+c]++;const m=Math.max(...w);return w.map(x=>x/m*.28)}
function freshness(p,t,w){const d=Number(p)-Number(t);if(d===0)return w;if(d===-1)return w*.38;if(d===1)return w*.62;return 0}
function apply(s,p,w){if(!p||w<=0)return;if(p.kind==='sum'){for(let n=0;n<28;n++){const d=Math.abs(n-p.sum);s[n]+=w*(d===0?2.8:d===1?.65:d===2?.22:0)}}else if(p.kind==='combo'){for(let n=0;n<28;n++){const c=classify(n);if(c.size===p.size)s[n]+=w*.72;if(c.oe===p.oe)s[n]+=w*.62;if(c.size===p.size&&c.oe===p.oe)s[n]+=w*.88}}else if(p.kind==='exclude'){let ex=[];if(p.value==='杀中')ex=[...Array(8)].map((_,i)=>10+i);if(p.value==='杀小边')ex=[...Array(10)].map((_,i)=>i);if(p.value==='杀大边')ex=[...Array(10)].map((_,i)=>18+i);for(let n=0;n<28;n++)s[n]+=ex.includes(n)?-w*.8:w*.18}}
async function fourCodes(rows,target){const score=baseScores();await Promise.all(SOURCES.map(async src=>{try{const h=await (await fetchT(src.url+(src.url.includes('?')?'&':'?')+'_='+Date.now())).text(),p=src.parse(h),w=p?freshness(p.issue,target,src.w):0;apply(score,p,w)}catch(e){console.log(src.id,'skip',e.name==='AbortError'?'timeout':e.message)}}));const freq=Array(28).fill(0),gap=Array(28).fill(30);rows.slice(0,30).forEach((r,i)=>{freq[r.sum]++;if(gap[r.sum]===30)gap[r.sum]=i});for(let n=0;n<28;n++)score[n]+=freq[n]*.058+Math.min(gap[n],15)*.013;return [...Array(28).keys()].sort((a,b)=>score[b]-score[a]||Math.abs(a-14)-Math.abs(b-14)).slice(0,4).sort((a,b)=>a-b);}
function settle(st,latest){st.comparisons ||= {};const x=st.comparisons[latest.issue];if(x&&x.status==='待'){x.actualSum=latest.sum;x.actualCombo=latest.combo;x.actualABC=latest.abc;x.autoResult=x.autoPicks?.includes(latest.combo)?'对':'错';x.codeResult=x.codes?.includes(latest.sum)?'对':'错';x.status='已开奖';x.settledAt=new Date().toISOString()}}
function trimComparisons(st){const ks=Object.keys(st.comparisons||{}).sort((a,b)=>Number(b)-Number(a)).slice(0,100),o={};for(const k of ks)o[k]=st.comparisons[k];st.comparisons=o}
async function tick(){let st={};try{st=JSON.parse(fs.readFileSync(FILE,'utf8'))}catch{}const d=await drawData(),latest=d.rows[0];settle(st,latest);const next=/^\d+$/.test(latest.issue)?String(BigInt(latest.issue)+1n):latest.issue+'-next';const ar=autoReference(d.rows),codes=await fourCodes(d.rows,next);st.comparisons ||= {};if(!st.comparisons[next])st.comparisons[next]={issue:next,autoPicks:ar.picks.map(x=>x.name),autoConfidence:ar.picks.map(x=>x.confidence),codes,status:'待',createdAt:new Date().toISOString()};trimComparisons(st);st.updatedAt=new Date().toISOString();st.latestDraw=latest;st.nextIssue=next;st.countdown=d.countdown;st.countdownEndsAt=d.countdownEndsAt;st.drawHistory=d.rows;st.autoReference={issue:next,...ar};st.consensus4={issue:next,codes};fs.writeFileSync(FILE,JSON.stringify(st,null,2));console.log('updated',latest.issue,'->',next,ar.picks.map(x=>x.name).join('/'),codes.join(','));}

const loops=Number(process.env.POLL_LOOPS||1),ms=Number(process.env.POLL_INTERVAL_MS||0);let ok=0;for(let i=0;i<loops;i++){try{await tick();ok++}catch(e){console.error('更新失败:',e.message)}if(i<loops-1&&ms)await sleep(ms)}if(!ok)process.exitCode=1;