import fs from 'fs';

const FILE='data/state.json';
const BASE='https://pc28.help';
const COMBOS=['大单','大双','小单','小双'];
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const classify=n=>({size:n<=13?'小':'大',oe:n%2?'单':'双',combo:(n<=13?'小':'大')+(n%2?'单':'双')});

async function fetchT(url,ms=8000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,redirect:'follow',headers:{'user-agent':'Mozilla/5.0 jnd28-updater','accept':'*/*'}});if(!r.ok)throw Error('HTTP '+r.status);return r}finally{clearTimeout(t)}}
function kenoABC(s){const a=String(s||'').split(/[,\s]+/).filter(Boolean).map(Number);if(a.length<19)return null;const g=x=>x.reduce((z,i)=>z+(a[i]||0),0)%10;return[g([1,4,7,10,13,16]),g([2,5,8,11,14,17]),g([3,6,9,12,15,18])]}
function parseCountdown(s){if(!s)return 0;const a=String(s).split(':').map(Number);if(a.some(Number.isNaN))return 0;if(a.length===2)return a[0]*60+a[1];if(a.length===3)return a[0]*3600+a[1]*60+a[2];return 0}
async function drawData(){const j=await (await fetchT(`${BASE}/api/keno.json?nbr=100&_=${Date.now()}`)).json();const a=Array.isArray(j?.data)?j.data:[];const rows=a.map(o=>{const abc=kenoABC(o.nbrs),issue=String(o.nbr||'');if(!abc||!issue)return null;const sum=abc.reduce((x,y)=>x+y,0);return{issue,abc:abc.join('+'),sum,...classify(sum),date:o.date||'',time:o.time||''}}).filter(Boolean);if(!rows.length)throw Error('开奖数据无法解析');const sec=parseCountdown(j.countdown);return{rows,countdown:j.countdown||'',countdownEndsAt:sec?Date.now()+sec*1000:null}}
function autoReference(rows){const recent=rows.slice(0,30),score=Object.fromEntries(COMBOS.map(c=>[c,1.2])),why=[];recent.forEach((r,i)=>score[r.combo]+=1.1*(1-i/Math.max(30,recent.length+1)));const l8=recent.slice(0,8),cnt=Object.fromEntries(COMBOS.map(c=>[c,0]));l8.forEach(r=>cnt[r.combo]++);if(l8.length>=4){const mn=Math.min(...Object.values(cnt));COMBOS.forEach(c=>{if(cnt[c]===mn)score[c]+=.9});why.push('近8期回补')}if(recent.length){const last=recent[0].combo,op={'大双':'小单','小单':'大双','大单':'小双','小双':'大单'}[last];let n=0;for(const r of recent){if(r.combo===last)n++;else break}if(n>=2){score[op]+=Math.min(2.4,n*.6);score[last]-=Math.min(1,n*.2);why.push(`${last}连开${n}期修正`)}}const rank=Object.entries(score).sort((a,b)=>b[1]-a[1]),total=rank.reduce((s,[,v])=>s+Math.max(v,.1),0);return{picks:rank.slice(0,2).map(([name,v],i)=>({name,confidence:Math.max(45,Math.min(72,Math.round(43+Math.max(v,.1)/total*58-i*2)))})),reason:why.slice(0,2).join('；')||'根据近期历史走势自动生成'}}
function settle(st,latest){st.comparisons ||= {};const x=st.comparisons[latest.issue];if(x&&x.status==='待'){x.actualSum=latest.sum;x.actualCombo=latest.combo;x.actualABC=latest.abc;x.autoResult=x.autoPicks?.includes(latest.combo)?'对':'错';x.status='已开奖';x.settledAt=new Date().toISOString()}}
function trimComparisons(st){const ks=Object.keys(st.comparisons||{}).sort((a,b)=>Number(b)-Number(a)).slice(0,100),o={};for(const k of ks)o[k]=st.comparisons[k];st.comparisons=o}
async function tick(){let st={};try{st=JSON.parse(fs.readFileSync(FILE,'utf8'))}catch{}const d=await drawData(),latest=d.rows[0],oldIssue=String(st.latestDraw?.issue||'');if(oldIssue===latest.issue){console.log('unchanged',latest.issue);return false}settle(st,latest);const next=/^\d+$/.test(latest.issue)?String(BigInt(latest.issue)+1n):latest.issue+'-next',ar=autoReference(d.rows);st.comparisons ||= {};if(!st.comparisons[next])st.comparisons[next]={issue:next,autoPicks:ar.picks.map(x=>x.name),autoConfidence:ar.picks.map(x=>x.confidence),status:'待',createdAt:new Date().toISOString()};trimComparisons(st);st.updatedAt=new Date().toISOString();st.latestDraw=latest;st.nextIssue=next;st.countdown=d.countdown;st.countdownEndsAt=d.countdownEndsAt;st.drawHistory=d.rows;st.autoReference={issue:next,...ar};delete st.consensus4;for(const x of Object.values(st.comparisons||{})){delete x.codes;delete x.codeResult}fs.writeFileSync(FILE,JSON.stringify(st,null,2));console.log('updated',latest.issue,'->',next,ar.picks.map(x=>x.name).join('/'));return true}

const loops=Number(process.env.POLL_LOOPS||1),ms=Number(process.env.POLL_INTERVAL_MS||0);let ok=0;for(let i=0;i<loops;i++){try{await tick();ok++}catch(e){console.error('更新失败:',e.message)}if(i<loops-1&&ms)await sleep(ms)}if(!ok&&loops===1)process.exitCode=1;