import fs from 'fs';
const BASE='https://pc28.help', FILE='data/state.json', C=['大单','大双','小单','小双'];
const cls=n=>(n<=13?'小':'大')+(n%2?'单':'双');
const val=(o,ks)=>{for(const k of ks)if(o?.[k]!=null&&o[k]!=='')return o[k];};
async function api(p){const r=await fetch(BASE+p,{headers:{'user-agent':'Mozilla/5.0 jnd28-updater'}});if(!r.ok)throw Error(`${p} HTTP ${r.status}`);return r.json();}
function parseKj(j){const a=Array.isArray(j)?j:Array.isArray(j?.data)?j.data:Array.isArray(j?.data?.list)?j.data.list:[];return a.map((r,i)=>{const issue=val(r,['nbr','issue','period','expect','qihao','no']);const raw=val(r,['number','sum','result','total','value']);const n=Number(Array.isArray(raw)?raw.reduce((x,y)=>x+Number(y),0):raw);return {issue:issue==null?'':String(issue),sum:n,combo:String(val(r,['combination','combo','type'])||cls(n)),idx:i};}).filter(x=>x.issue&&Number.isFinite(x.sum));}
function kenoPc(s){const a=Array.isArray(s)?s:String(s||'').split(/[,\s]+/).filter(Boolean).map(Number);if(a.length<19)return null;const g=idx=>idx.reduce((t,i)=>t+(Number(a[i])||0),0)%10;const x=g([1,4,7,10,13,16]),y=g([2,5,8,11,14,17]),z=g([3,6,9,12,15,18]);return x+y+z;}
async function rows(){try{const j=await api('/api/kj.json?nbr=100'),r=parseKj(j);if(r.length)return {source:'kj',rows:r};}catch(e){console.log('kj fallback',e.message)}const j=await api('/api/keno.json?nbr=100');const a=Array.isArray(j)?j:Array.isArray(j?.data)?j.data:[];const r=a.map((o,i)=>{const n=kenoPc(val(o,['nbrs','numbers','result']));const issue=val(o,['nbr','issue','period','expect','qihao','no']);return {issue:issue==null?'':String(issue),sum:n,combo:Number.isFinite(n)?cls(n):'',idx:i};}).filter(x=>x.issue&&Number.isFinite(x.sum));if(!r.length)throw Error('KJ与Keno均无法解析');return {source:'keno',rows:r};}
function predict(rs,mode){const n=mode===1?20:mode===2?36:100, part=rs.slice(0,n), s=Object.fromEntries(C.map(x=>[x,0]));part.forEach((r,i)=>{if(C.includes(r.combo))s[r.combo]+=mode===2?Math.max(.25,1-i*.024):1});if(mode===3){for(const r of rs.slice(0,5))if(C.includes(r.combo))s[r.combo]-=.2;}const rank=C.map(c=>({c,s:s[c]})).sort((a,b)=>b.s-a.s), total=rank.reduce((a,b)=>a+b.s,0)||1;return {combos:[rank[0].c,rank[1].c],kill:rank[3].c,confidence:Math.min(86,Math.round((rank[0].s+rank[1].s)/total*100))};}
function settle(a,sim,actual){const cur=a.current;if(cur?.issue===actual.issue){const hit=cur.combos.includes(actual.combo);a.records.unshift({issue:actual.issue,combos:cur.combos,kill:cur.kill,confidence:cur.confidence,actualCombo:actual.combo,actualSum:actual.sum,comboHit:hit,killSuccess:actual.combo!==cur.kill,settledAt:new Date().toISOString()});a.records=a.records.slice(0,100);a.current=null;}const p=sim.pending;if(p?.issue===actual.issue){const hit=p.combos.includes(actual.combo);if(hit){sim.points+=sim.stake;sim.net+=sim.stake;sim.step=1;sim.stake=5}else{const loss=sim.stake*2;sim.points-=loss;sim.net-=loss;sim.step++;sim.stake*=2}sim.pending=null;if(sim.points>=500||sim.points<=0||sim.points<sim.stake*2){const ok=sim.points>=500;ok?sim.success++:sim.fail++;sim.history.unshift({round:sim.round,result:ok?'成功':'失败',endPoints:Math.max(0,sim.points),endedAt:new Date().toISOString()});sim.history=sim.history.slice(0,100);sim.round++;sim.points=300;sim.step=1;sim.stake=5;}}}
async function tick(){const st=JSON.parse(fs.readFileSync(FILE,'utf8')), d=await rows(), latest=d.rows[0];if(!latest)throw Error('没有可用开奖');console.log('开奖数据源:',d.source,'期号:',latest.issue,'和值:',latest.sum);st.latestDraw={issue:latest.issue,sum:latest.sum,combo:latest.combo};st.nextIssue=/^\d+$/.test(latest.issue)?String(BigInt(latest.issue)+1n):latest.issue+'-next';for(const [i,id] of ['a1','a2','a3'].entries()){const a=st.algorithms[id],sim=st.simulations[id];settle(a,sim,latest);const p=predict(d.rows,i+1);if(!a.current||a.current.issue!==st.nextIssue)a.current={issue:st.nextIssue,...p,createdAt:new Date().toISOString()};if(!sim.pending&&p.confidence>=50)sim.pending={issue:st.nextIssue,combos:[...p.combos],confidence:p.confidence,createdAt:new Date().toISOString()};}st.updatedAt=new Date().toISOString();fs.writeFileSync(FILE,JSON.stringify(st,null,2));console.log('updated',latest.issue,'->',st.nextIssue);}
const loops=Number(process.env.POLL_LOOPS||1), ms=Number(process.env.POLL_INTERVAL_MS||0);let ok=0;for(let i=0;i<loops;i++){try{await tick();ok++}catch(e){console.error('本轮更新失败:',e.message)}if(i<loops-1&&ms)await new Promise(r=>setTimeout(r,ms));}if(!ok)process.exitCode=1;